const MAPPED_COUNTRIES = [
    {"value": "US", "label": "United States", "latitude": 37, "longitude": -95},
    {"value": "AR", "label": "Argentina", "longitude": -64, "latitude": -34},
    {"value": "AU", "label": "Australia", "longitude": 133, "latitude": -27},
    {"value": "AT", "label": "Austria", "longitude": 14, "latitude": 47.6},
    {"value": "BE", "label": "Belgium", "longitude": 4, "latitude": 50.9},
    {"value": "BO", "label": "Bolivia, Plurinational State of", "longitude": -65, "latitude": -17},
    {"value": "BR", "label": "Brazil", "longitude": -47, "latitude": -15.8},
    {"value": "CA", "label": "Canada", "longitude": -106, "latitude": 58.8},
    {"value": "CL", "label": "Chile", "longitude": -71, "latitude": -35},
    {"value": "CO", "label": "Colombia", "longitude": -74, "latitude": 4},
    {"value": "CR", "label": "Costa Rica", "longitude": -84, "latitude": 9.9},
    {"value": "CZ", "label": "Czech Republic", "longitude": 15.5, "latitude": 49.7},
    {"value": "DK", "label": "Denmark", "longitude": 10, "latitude": 55.7},
    {"value": "DO", "label": "Dominican Republic", "longitude": -70.5, "latitude": 18.9},
    {"value": "EC", "label": "Ecuador", "longitude": -78.5, "latitude": -1.8},
    {"value": "EG", "label": "Egypt", "longitude": 30.8, "latitude": 26.8},
    {"value": "SV", "label": "El Salvador", "longitude": -88.9, "latitude": 13.7},
    {"value": "EE", "label": "Estonia", "longitude": 25, "latitude": 58.7},
    {"value": "FI", "label": "Finland", "longitude": 26, "latitude": 64.9},
    {"value": "FR", "label": "France", "longitude": 2.3, "latitude": 46.7},
    {"value": "DE", "label": "Germany", "longitude": 10.5, "latitude": 51.2},
    {"value": "GT", "label": "Guatemala", "longitude": -90.4, "latitude": 15.7},
    {"value": "HN", "label": "Honduras", "longitude": -86.9, "latitude": 15.2},
    {"value": "HU", "label": "Hungary", "longitude": 19.5, "latitude": 47.2},
    {"value": "IS", "label": "Iceland", "longitude": -18.5, "latitude": 64.9},
    {"value": "IN", "label": "India", "longitude": 78, "latitude": 20.6},
    {"value": "ID", "label": "Indonesia", "longitude": 117.5, "latitude": -2.1},
    {"value": "IE", "label": "Ireland", "longitude": -8.2, "latitude": 53.4},
    {"value": "IL", "label": "Israel", "longitude": 35.2, "latitude": 31.5},
    {"value": "IT", "label": "Italy", "longitude": 12.6, "latitude": 41.9},
    {"value": "JP", "label": "Japan", "longitude": 138.2, "latitude": 36.2},
    {"value": "KE", "label": "Kenya", "longitude": 37.9, "latitude": 1.3},
    {"value": "LU", "label": "Luxembourg", "longitude": 6.1, "latitude": 49.8},
    {"value": "MX", "label": "Mexico", "longitude": -102.6, "latitude": 23.6},
    {"value": "NL", "label": "Netherlands", "longitude": 5.3, "latitude": 52.1},
    {"value": "NZ", "label": "New Zealand", "longitude": 174.7, "latitude": -40.9},
    {"value": "NI", "label": "Nicaragua", "longitude": -85.2, "latitude": 12.9},
    {"value": "NG", "label": "Nigeria", "longitude": 8.7, "latitude": 9.1},
    {"value": "NO", "label": "Norway", "longitude": 10.8, "latitude": 60.5},
    {"value": "PA", "label": "Panama", "longitude": -80.6, "latitude": 8.6},
    {"value": "PY", "label": "Paraguay", "longitude": -58.4, "latitude": -23.4},
    {"value": "PE", "label": "Peru", "longitude": -76.3, "latitude": -9.2},
    {"value": "PL", "label": "Poland", "longitude": 19.4, "latitude": 51.9},
    {"value": "PT", "label": "Portugal", "longitude": -8.5, "latitude": 39.4},
    {"value": "RO", "label": "Romania", "longitude": 24.9, "latitude": 45.9},
    {"value": "RU", "label": "Russian Federation", "longitude": 105.3, "latitude": 61.5},
    {"value": "SA", "label": "Saudi Arabia", "longitude": 45, "latitude": 23.9},
    {"value": "RS", "label": "Serbia", "longitude": 20.5, "latitude": 44},
    {"value": "ZA", "label": "South Africa", "longitude": 25, "latitude": -28.5},
    {"value": "KR", "label": "Korea, Republic of", "longitude": 127.8, "latitude": 36.6},
    {"value": "ES", "label": "Spain", "longitude": -4.8, "latitude": 40.5},
    {"value": "SE", "label": "Sweden", "longitude": 15, "latitude": 62},
    {"value": "CH", "label": "Switzerland", "longitude": 8, "latitude": 47},
    {"value": "TZ", "label": "Tanzania, United Republic of", "longitude": 35, "latitude": -6},
    {"value": "TR", "label": "Turkey", "longitude": 35, "latitude": 39},
    {"value": "UG", "label": "Uganda", "longitude": 32, "latitude": 1},
    {"value": "UA", "label": "Ukraine", "longitude": 31, "latitude": 49},
    {"value": "AE", "label": "United Arab Emirates", "longitude": 53.8, "latitude": 23.4},
    {"value": "GB", "label": "United Kingdom", "longitude": 3.4, "latitude": 55},
    {"value": "UY", "label": "Uruguay", "longitude": 55.7, "latitude": 32.5},
    {"value": "ZW", "label": "Zimbabwe", "longitude": 29.1, "latitude": 19}
];

export { MAPPED_COUNTRIES };
