export const MAPPED_COUNTRIES = [
    {"value": "US", "label": "United States", "lat": 37, "lng": -95, "id": 1, "text": "United States"},
    {"value": "AR", "label": "Argentina", "lat": -34, "lng": -64, "id": 2, "text": "Argentina"},
    {"value": "AU", "label": "Australia", "lat": -27, "lng": 133, "id": 3, "text": "Australia"},
    {"value": "AT", "label": "Austria", "lat": 47.6, "lng": 14, "id": 4, "text": "Austria"},
    {"value": "BE", "label": "Belgium", "lat": 50.9, "lng": 4, "id": 5, "text": "Belgium"},
    {"value": "BO", "label": "Bolivia", "lat": -17, "lng": -65, "id": 6, "text": "Bolivia"},
    {"value": "BR", "label": "Brazil", "lat": -15.8, "lng": -47, "id": 7, "text": "Brazil"},
    {"value": "CA", "label": "Canada", "lat": 58.8, "lng": -106, "id": 8, "text": "Canada"},
    {"value": "CL", "label": "Chile", "lat": -35, "lng": -71, "id": 9, "text": "Chile"},
    {"value": "CO", "label": "Colombia", "lat": 4, "lng": -74, "id": 10, "text": "Colombia"},
    {"value": "CR", "label": "Costa Rica", "lat": 9.9, "lng": -84, "id": 11, "text": "Costa Rica"},
    {"value": "CZ", "label": "Czech Republic", "lat": 49.7, "lng": 15.5, "id": 12, "text": "Czech Republic"},
    {"value": "DK", "label": "Denmark", "lat": 55.7, "lng": 10, "id": 13, "text": "Denmark"},
    {"value": "DO", "label": "Dominican Republic", "lat": 18.9, "lng": -70.5, "id": 14, "text": "Dominican Republic"},
    {"value": "EC", "label": "Ecuador", "lat": -1.8, "lng": -78.5, "id": 15, "text": "Ecuador"},
    {"value": "EG", "label": "Egypt", "lat": 26.8, "lng": 30.8, "id": 16, "text": "Egypt"},
    {"value": "SV", "label": "El Salvador", "lat": 13.7, "lng": -88.9, "id": 17, "text": "El Salvador"},
    {"value": "EE", "label": "Estonia", "lat": 58.7, "lng": 25, "id": 18, "text": "Estonia"},
    {"value": "FI", "label": "Finland", "lat": 64.9, "lng": 26, "id": 19, "text": "Finland"},
    {"value": "FR", "label": "France", "lat": 46.7, "lng": 2.3, "id": 20, "text": "France"},
    {"value": "DE", "label": "Germany", "lat": 51.2, "lng": 10.5, "id": 21, "text": "Germany"},
    {"value": "GT", "label": "Guatemala", "lat": 15.7, "lng": -90.4, "id": 22, "text": "Guatemala"},
    {"value": "HN", "label": "Honduras", "lat": 15.2, "lng": -86.9, "id": 23, "text": "Honduras"},
    {"value": "HU", "label": "Hungary", "lat": 47.2, "lng": 19.5, "id": 24, "text": "Hungary"},
    {"value": "IS", "label": "Iceland", "lat": 64.9, "lng": -18.5, "id": 25, "text": "Iceland"},
    {"value": "IN", "label": "India", "lat": 20.6, "lng": 78, "id": 26, "text": "India"},
    {"value": "ID", "label": "Indonesia", "lat": -2.1, "lng": 117.5, "id": 27, "text": "Indonesia"},
    {"value": "IE", "label": "Ireland", "lat": 53.4, "lng": -8.2, "id": 28, "text": "Ireland"},
    {"value": "IL", "label": "Israel", "lat": 31.5, "lng": 35.2, "id": 29, "text": "Israel"},
    {"value": "IT", "label": "Italy", "lat": 41.9, "lng": 12.6, "id": 30, "text": "Italy"},
    {"value": "JP", "label": "Japan", "lat": 36.2, "lng": 138.2, "id": 31, "text": "Japan"},
    {"value": "KE", "label": "Kenya", "lat": 1.3, "lng": 37.9, "id": 32, "text": "Kenya"},
    {"value": "LU", "label": "Luxembourg", "lat": 49.8, "lng": 6.1, "id": 33, "text": "Luxembourg"},
    {"value": "MX", "label": "Mexico", "lat": 23.6, "lng": -102.6, "id": 34, "text": "Mexico"},
    {"value": "NL", "label": "Netherlands", "lat": 52.1, "lng": 5.3, "id": 35, "text": "Netherlands"},
    {"value": "NZ", "label": "New Zealand", "lat": -40.9, "lng": 174.7, "id": 36, "text": "New Zealand"},
    {"value": "NI", "label": "Nicaragua", "lat": 12.9, "lng": -85.2, "id": 37, "text": "Nicaragua"},
    {"value": "NG", "label": "Nigeria", "lat": 9.1, "lng": 8.7, "id": 38, "text": "Nigeria"},
    {"value": "NO", "label": "Norway", "lat": 60.5, "lng": 10.8, "id": 39, "text": "Norway"},
    {"value": "PA", "label": "Panama", "lat": 8.6, "lng": -80.6, "id": 40, "text": "Panama"},
    {"value": "PY", "label": "Paraguay", "lat": -23.4, "lng": -58.4, "id": 41, "text": "Paraguay"},
    {"value": "PE", "label": "Peru", "lat": -9.2, "lng": -76.3, "id": 42, "text": "Peru"},
    {"value": "PL", "label": "Poland", "lat": 51.9, "lng": 19.4, "id": 43, "text": "Poland"},
    {"value": "PT", "label": "Portugal", "lat": 39.4, "lng": -8.5, "id": 44, "text": "Portugal"},
    {"value": "RO", "label": "Romania", "lat": 45.9, "lng": 24.9, "id": 45, "text": "Romania"},
    {"value": "RU", "label": "Russia", "lat": 61.5, "lng": 105.3, "id": 46, "text": "Russia"},
    {"value": "SA", "label": "Saudi Arabia", "lat": 23.9, "lng": 45, "id": 47, "text": "Saudi Arabia"},
    {"value": "RS", "label": "Serbia", "lat": 44, "lng": 20.5, "id": 48, "text": "Serbia"},
    {"value": "ZA", "label": "South Africa", "lat": -28.5, "lng": 25, "id": 49, "text": "South Africa"},
    {"value": "KR", "label": "South Korea", "lat": 36.6, "lng": 127.8, "id": 50, "text": "South Korea"},
    {"value": "ES", "label": "Spain", "lat": 40.5, "lng": -4.8, "id": 51, "text": "Spain"},
    {"value": "SE", "label": "Sweden", "lat": 62, "lng": 15, "id": 52, "text": "Sweden"},
    {"value": "CH", "label": "Switzerland", "lat": 47, "lng": 8, "id": 53, "text": "Switzerland"},
    {"value": "TZ", "label": "Tanzania", "lat": -6, "lng": 35, "id": 54, "text": "Tanzania"},
    {"value": "TR", "label": "Turkey", "lat": 39, "lng": 35, "id": 55, "text": "Turkey"},
    {"value": "UG", "label": "Uganda", "lat": 1, "lng": 32, "id": 56, "text": "Uganda"},
    {"value": "UA", "label": "Ukraine", "lat": 49, "lng": 31, "id": 57, "text": "Ukraine"},
    {"value": "AE", "label": "United Arab Emirates", "lat": 23.4, "lng": 53.8, "id": 58, "text": "United Arab Emirates"},
    {"value": "GB", "label": "United Kingdom", "lat": 55, "lng": 3.4, "id": 59, "text": "United Kingdom"},
    {"value": "UY", "label": "Uruguay", "lat": 32.5, "lng": 55.7, "id": 60, "text": "Uruguay"},
    {"value": "ZW", "label": "Zimbabwe", "lat": 19, "lng": 29.1, "id": 61, "text": "Zimbabwe"}
];
